language: python
python:
  - 3.6
  - nightly
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install coverage coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py build
  - python setup.py install
  - coverage run all_tests.py
  - coveralls

