language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - nightly
  
install: 
  - pip install .
  - pip install nose coverage
  - pip install coveralls

# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package astar

after_sucess:
  coveralls
